---
grafana_ini:
  server:
    http_addr: "0.0.0.0"
    http_port: 3000
    cert_key: /etc/grafana/tls/tls.pem
    cert_file: /etc/grafana/tls/tls.cert
    protocol: https
  security:
    admin_user: admin
    admin_password: "changeMe0815!"
    secret_key: "chnageMe0815!"

grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: https://localhost:9090
    basicAuth: true
    basicAuthUser: "prometheus"
    secureJsonData:
      basicAuthPassword: "changeMe0815!"
    jsonData:
      tlsSkipVerify: true
