---
- hosts: prometheus-server
  become: true
  pre_tasks:
    - name: "Create system group {{ prometheus_system_group }}"
      ansible.builtin.group:
        name: "{{ prometheus_system_group }}"
        system: true
        state: present

    - name: "Create system user {{ prometheus_system_user }}"
      ansible.builtin.user:
        name: "{{ prometheus_system_user }}"
        system: true
        shell: "/usr/sbin/nologin"
        group: "{{ prometheus_system_group }}"
        home: "{{ prometheus_config_dir }}"
        create_home: false

    - name: Create prometheus cert dir
      ansible.builtin.file:
        path: "/etc/prometheus/tls"
        state: directory
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"

    - name: Generate OpenSSL private key
      community.crypto.openssl_privatekey:
        path: /etc/prometheus/tls/tls.pem
        size: 4096
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
        mode: "0640"

    - name: Generate Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: /etc/prometheus/tls/tls.cert
        privatekey_path: /etc/prometheus/tls/tls.pem
        provider: selfsigned
        owner: "{{ prometheus_system_user }}"
        group: "{{ prometheus_system_group }}"
        mode: "0640"
  roles:
    - prometheus.prometheus.prometheus
